COMMENTS_PER_PAGE_LIMIT = 100
ITEMS_PER_GROUP_LIMIT = 100
GROUPS_PER_CATEGORY_LIMIT = 15
CATEGORIES_LIMIT = 15

RESULT_FILE_NAME_PREFIX = 'results'
RESULT_FOLDER_NAME = "results"

DEFAULT_SELENIUM_DRIVER = "Chrome"

APPLICATION_MODE = "from_file"

APPLICATION_MODES_LIST = ["clean", "from_file"] #append new
