COMMENTS_PER_PAGE_LIMIT = 100
ITEMS_PER_GROUP_LIMIT = 100
GROUPS_PER_CATEGORY_LIMIT = 15
CATEGORIES_LIMIT = 15

SITE_SCRAP_RESULT_FILE_NAME_PREFIX = 'results'
BOW_RESULT_FILE_NAME_PREFIX = 'bow'
BIGRAMM_RESULT_FILE_NAME_PREFIX = 'bigramm'

RESULT_FOLDER_NAME = "results"
RESULT_BOW_SUB_FOLDER_NAME = "bow"
RESULT_BIGRAMM_SUB_FOLDER_NAME = "bigramm"

SITE_SCRAP_RELATIVE_FILE_PATH_STRING = RESULT_FOLDER_NAME + "/" + SITE_SCRAP_RESULT_FILE_NAME_PREFIX + "_{}.json"
BOW_RELATIVE_FILE_PATH_STRING = RESULT_FOLDER_NAME + "/" + RESULT_BOW_SUB_FOLDER_NAME + "/" + BOW_RESULT_FILE_NAME_PREFIX + "_{}.json"
BIGRAMM_RELATIVE_FILE_PATH_STRING = RESULT_FOLDER_NAME + "/" + RESULT_BIGRAMM_SUB_FOLDER_NAME + "/" + BIGRAMM_RESULT_FILE_NAME_PREFIX + "_{}.json"

DEFAULT_SELENIUM_DRIVER = "Chrome"

APPLICATION_MODE = "from_file"

APPLICATION_MODES_LIST = ["clean", "from_file"] #append new
